# Generated by Django 5.2.13 on 2026-05-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0298_pluggable_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(default='GBP', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.CreateModel(
            name='SubEventSessionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(max_length=200, null=True)),
                ('subevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_blocks', to='pretixbase.subevent')),
            ],
            options={
                'verbose_name': 'Session block',
                'verbose_name_plural': 'Session blocks',
                'ordering': ['date_from'],
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='session_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='pretixbase.subeventsessionblock'),
        ),
    ]
